from datetime import date
from sound import Sound
def yukselt():
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
    Sound.volume_up()
def dusur():
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
    Sound.volume_down()
def sifir():
    Sound.volume_min()
def full():
    Sound.volume_max()
